import requests
import time
import random
import urllib.parse
from colorama import Fore, Style

class WAFEngine:
    """
    Intelligent WAF Detection and Payload Evasion Engine.
    """
    WAF_SIGNATURES = {
        "Cloudflare": {"headers": {"server": "cloudflare"}, "content": ["cloudflare-nginx", "cf-ray"]},
        "AWS WAF": {"headers": {"server": "awselb"}, "content": ["aws waf", "403 forbidden"]},
        "Akamai": {"headers": {"server": "akamai"}, "content": ["akamai ghost"]},
        "Sucuri": {"headers": {"server": "sucuri"}, "content": ["sucuri web site firewall"]},
        "Wordfence": {"headers": {}, "content": ["generated by wordfence", "your access to this site has been limited"]},
        "F5 BIG-IP": {"headers": {"server": "big-ip"}, "content": []},
    }

    def __init__(self):
        self.detected_waf = None
        self.rate_limit_delay = 0

    def detect(self, target_url):
        """Detect WAF presence using headers and a generic blocked payload."""
        print(f"[{Fore.BLUE}*{Style.RESET_ALL}] Analyzing target for Web Application Firewalls (WAF)...")
        try:
            # Send a normal request to check headers
            r_normal = requests.get(target_url, timeout=5)
            self._analyze_response(r_normal)

            # Send a malicious request to trigger block pages
            malicious_url = f"{target_url}?test=<script>alert(1)</script> UNION SELECT 1,2,3--"
            r_mal = requests.get(malicious_url, timeout=5)
            
            if r_mal.status_code in [403, 406, 429, 503]:
                self._analyze_response(r_mal)
                
            if self.detected_waf:
                print(f"  [{Fore.RED}!{Style.RESET_ALL}] WAF Detected: {Fore.YELLOW}{self.detected_waf}{Style.RESET_ALL}")
                # Increase delay if WAF is aggressive
                self.rate_limit_delay = 0.5
            else:
                print(f"  [{Fore.GREEN}+{Style.RESET_ALL}] No WAF detected. Proceeding with standard speeds.")
                
        except requests.RequestException:
            pass
            
        return self.detected_waf

    def _analyze_response(self, response):
        headers_lower = {k.lower(): v.lower() for k, v in response.headers.items()}
        text_lower = response.text.lower()
        
        for waf_name, sig in self.WAF_SIGNATURES.items():
            # Check Headers
            for h_key, h_val in sig["headers"].items():
                if h_key in headers_lower and h_val in headers_lower[h_key]:
                    self.detected_waf = waf_name
                    return
                    
            # Check Content
            for c_val in sig["content"]:
                if c_val in text_lower:
                    self.detected_waf = waf_name
                    return

    def evade(self, payload):
        """Intelligently obfuscate payload based on the detected WAF."""
        if not self.detected_waf:
            return payload # Send raw if no WAF
            
        # Apply random evasion techniques
        techniques = [self._url_encode, self._double_url_encode, self._unicode_encode]
        chosen_tech = random.choice(techniques)
        evaded = chosen_tech(payload)
        return evaded
        
    def _url_encode(self, payload):
        """Standard URL encoding of special chars."""
        return urllib.parse.quote(payload)
        
    def _double_url_encode(self, payload):
        """Bypasses WAFs that decode only once before analyzing."""
        return urllib.parse.quote(urllib.parse.quote(payload))
        
    def _unicode_encode(self, payload):
        """Unicode encoding (e.g. < -> %u003c)"""
        encoded = ""
        for char in payload:
            if not char.isalnum():
                encoded += f"%u00{hex(ord(char))[2:]}"
            else:
                encoded += char
        return encoded

    def request(self, method, url, **kwargs):
        """Wrapper for requests that applies rate limiting."""
        if self.rate_limit_delay > 0:
            time.sleep(self.rate_limit_delay + random.uniform(0.1, 0.5))
        return requests.request(method, url, **kwargs)
